export const TAXPAYERS_CACHE_REPOSITORY = 'TAXPAYERS_CACHE_REPOSITORY';
export const TAXPAYERS_DIRECTORY_REPOSITORY = 'TAXPAYERS_DIRECTORY_REPOSITORY';
export const TAXPAYER_PROVIDER_FACTORY = 'TAXPAYER_PROVIDER_FACTORY';
