export enum CompanyModule {
  NEWS = 'NEWS',
  EXCHANGE_RATES = 'EXCHANGE_RATES',
  MEMBERS = 'MEMBERS',
  EVENTS = 'EVENTS',
  ADS = 'ADS',
  SCHEDULES = 'SCHEDULES',
  SCHEDULE_BREAKS = 'SCHEDULE_BREAKS',
  SERVICES = 'SERVICES',
}
